### ISSUE TITLE
Icon Layouts 

### ISSUE THREAD

**Issue by jawonder** [FlashBackiOS/FlashBack#2]
It’s not restoring icon layouts properly . I backup a theme with 4x4 rows and columns and and then do a new setup with a 3x3 rows and columns . I then restored the 4x4 while on the 3x3 and it kept the 3x3 layout after restoring the 4x4. I had to copy “DesiredIconState.plist” and “IconSupportState.plist” that i had saved for that 4x4 setup to SpringBoard to get the icons back the way they were.

I do see both IconSupportState.plist and DesiredIconState.plist in SBFolder. Maybe something to do with the renaming of Springboard to SBFolder

**Comment by pogmommy** [comment]
Fixed as of version 1.5.1
